# Generated by Django 4.2.5 on 2023-09-16 16:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('clarity', models.CharField(choices=[('I1', 'I1'), ('SI1', 'SI1'), ('VS1', 'VS1'), ('VVS1', 'VVS1'), ('IF', 'IF')], default='I1', max_length=5)),
                ('cut', models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Poor', max_length=10)),
                ('color', models.CharField(choices=[('J', 'J'), ('I', 'I'), ('H', 'H'), ('G', 'G'), ('F', 'F'), ('E', 'E'), ('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A')], default='J', max_length=2)),
                ('depth', models.DecimalField(decimal_places=2, default=55, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('55')), django.core.validators.MaxValueValidator(Decimal('70'))])),
                ('table', models.DecimalField(decimal_places=2, default=54, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('54')), django.core.validators.MaxValueValidator(Decimal('64'))])),
                ('prediction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
